version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development

  worker:
    build: .
    command: rq worker --url redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
